require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  NewCops: enable
  Exclude:
    - node_modules/**/*
    - public/**/*
    - vendor/**/*

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false # allow spaces inside hash braces
Style/ClassMethodsDefinitions:
  Enabled: false # allow class methods to be defined before instance methods
Style/ClassAndModuleChildren:
  Enabled: false # allow nested classes and modules
Style/ModuleFunction:
  Enabled: false
Style/OpenStructUse:
  Enabled: false # allow OpenStruct
Style/TrailingCommaInArguments:
  Enabled: false # allow trailing commas in method calls
Style/TrailingCommaInHashLiteral:
  Enabled: false # allow trailing commas in hashes

RSpec:
  Enabled: true # enable rubocop-rspec cops
RSpec/DescribeClass:
  Enabled: false # ignore missing comments on classes
RSpec/MultipleExpectations:
  Enabled: false # allow multiple expectations in a single example
RSpec/ExampleLength:
  Max: 20 # set max example length to 20 lines
