plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-minitest

inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  NewCops: enable
  Exclude:
    - node_modules/**/*
    - public/**/*
    - vendor/**/*

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false # allow spaces inside hash braces
Style/ClassMethodsDefinitions:
  Enabled: false # allow class methods to be defined before instance methods
Style/ClassAndModuleChildren:
  Enabled: false # allow nested classes and modules
Style/ModuleFunction:
  Enabled: false
Style/OpenStructUse:
  Enabled: false # allow OpenStruct
Style/TrailingCommaInArguments:
  Enabled: false # allow trailing commas in method calls
Style/TrailingCommaInHashLiteral:
  Enabled: false # allow trailing commas in hashes

Minitest:
  Enabled: true
