require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  NewCops: enable
  Exclude:
    - node_modules/**/*
    - public/**/*
    - vendor/**/*

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false # allow spaces inside hash braces
Style/OpenStructUse:
  Enabled: false # allow OpenStruct
Style/TrailingCommaInArguments:
  Enabled: false # allow trailing commas in method calls
Style/TrailingCommaInHashLiteral:
  Enabled: false # allow trailing commas in hashes

RSpec:
  Enabled: true # enable rubocop-rspec cops
RSpec/DescribeClass:
  Enabled: false # ignore missing comments on classes
