require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  NewCops: enable
  Exclude:
    - node_modules/**/*
    - public/**/*
    - vendor/**/*

RSpec:
  Enabled: true # enable rubocop-rspec cops
RSpec/DescribeClass:
  Enabled: false # ignore missing comments on classes
Style/OpenStructUse:
  Enabled: false # allow OpenStruct
