name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    env:
      CI: "true"
      NO_COVERAGE: "true"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      - name: Generate lockfile
        run: bundle lock
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake
